# Generated by Django 5.0.2 on 2024-02-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='image',
            field=models.ImageField(default='default_poster.jpg', upload_to='film_images/'),
        ),
    ]
